//
// Created by martin on 01.12.19.
//

#include <iostream>
#include <unordered_map>
#include <blocksci/core/dedup_address.hpp>
#include <blocksci/chain.hpp>
#include <blocksci/address.hpp>
#include <internal/address_info.hpp>

//std::unordered_map<std::string, std::vector<std::string>> tags;

std::map<std::string, std::map<std::string, std::string>> getTagsMapping();

auto getTags(blocksci::Blockchain& chain) {
    //tags.insert("Exchange", std::vector<std::string>{"asdfasdfadsf", "bsd"});
    std::unordered_map<blocksci::DedupAddress, std::string> convertedTags;

    auto tagsMapping = getTagsMapping();

    for (auto& category : tagsMapping) {
        for (auto& tag : category.second) {
            auto address = blocksci::getAddressFromString(tag.second, chain.getAccess());
            if (address) {
                convertedTags.insert({
                    blocksci::DedupAddress{address->scriptNum, blocksci::dedupType(address->type)},
                    category.first + "(" + tag.first + ")"
                });
            }
        }
    }

    return convertedTags;
}


std::map<std::string, std::map<std::string, std::string>> getTagsMapping() {
    std::map<std::string, std::map<std::string, std::string>> tagsMapping{
        {{"Exchange", {
            {"Bitstamp.net", "38f8RHFQ8v6avZqCmaYTga5bTYiuhoM6fh"},
            {"LocalBitcoins.com-old", "14S2cUvnYig1rvejbPWqJDsFAhh1F13Kra"},
            {"LocalBitcoins.com", "1FtMAGbhsxRNc3GBUunKRk57e5hxdqYwV9"},
            {"Luno.com", "17ac9tXHxu1nxdLgLu9WYk7vR8ggFN5GkH"},
            {"BTC-e.com-old", "171LFo1rr4oSE6CDkV7NxyCfwX2sMXJZtP"},
            {"BTC-e.com-output", "1FsVcdeHbpvUVT3gjeuVR2ZSDnpcsJMsLL"},
            {"BTC-e.com", "193JhFJVNzKjtnQgJgTG1h5hJdTtWtNfNT"},
            {"Poloniex.com", "17A16QmavnUfCW11DAApiJxp7ARnxN5pGX"},
            {"Bittrex.com", "14cQRmViAzVKa277gZznByGZtnrVPQc8Lr"},
            {"Huobi.com-2", "1DTJTKsoCE8S4QeKpBDXmdbkSWSBvxRXL3"},
            {"Huobi.com", "19hx1B4pTDsBAYJJYYrj1t6bcVw1e9omuH"},
            {"Bter.com", "1GNSmRooZUWj3TvWduYGDGjmmAnarSsYXb"},
            {"MaiCoin.com", "18uRuCuEsEA3LS7nGShr7ZbSUNwsbrYALf"},
            {"Kraken.com", "1AnwDVbwsLBVwRfqN2x9Eo4YEJSPXo2cwG"},
            {"HitBtc.com-old", "16jTAi7cB5uhi3En3Howq7XUdUM1mB2GH8"},
            {"HitBtc.com", "3QGfWQoEcUCfJGAg5dYrHmuCU38xcZNWLu"},
            {"ExchangeMyCoins.com", "1M5NczBKPQSyFP2DzouXGAHeqoAYDQv2WC"},
            {"Coingi.com", "15VbGLMQWCqEFhXFk9iaS3xLaURFYuxMvd"},
            {"1Coin.com", "1GqWeVySuv96nFybv27W7ULQ1rzDHeAi7a"},
            {"Zyado.com-old", "1Q85285KFsnWDkLxLc3dXwGHtFL3BhotWg"},
            {"Zyado.com", "1Mb4JKCVaGkdF5NuxufwhFy2f8u1WUoVKc"},
            {"Coinbroker.io", "1PLjsBGtf7rJNuxaeWWReDhkLk9bZstGo"},
            {"UseCryptos.com", "1QELiiEgw997EycjPu9wmFh9u7CRctk8J6"},
            {"Ccedk.com", "1MudcrRWzrjUgn1ugzh2ve4gpCpS8vWyHL"},
            {"EmpoEX.com", "123DvCXxfH24dM57qjGLixN3ENjnuEZwGe"},
            {"Coinimal.com", "1MLgaxVMmhscDAN3Mjg1wPYNvSAG4mMDbf"},
            {"Bitso.com", "1DDwrxz5MC98Pfrjp4PcQiErx7wz6FJnRJ"},
            {"Exchange-Credit.ru", "1Q7PTybd4ybhKAi8a9pph6NjVCEMVfUhBt"},
            {"Cryptonit.net-old", "164Bqayn7fuGssWTqfRQ5NcuepJpGWV24V"},
            {"Cryptonit.net", "1D1ZqQedv56GoasmmE5yaomNMJq6bsNjkz"},
            {"CoinChimp.com", "1JnSk5wGTigae183N9TGZXHKJTtGA8DNfm"},
            {"BitcoinVietnam.com.vn", "15fQXokp2fr3ygHu2nzh3R4N7qtTnrmk66"},
            {"CoinArch.com", "1LX78tyJGCoDnYbYZcNU3rKVw4w3u4kmrp"},
            {"Indacoin.com", "1LBuYdxJsDBxkgdjH7kyuD8dkWu1EMZEgP"},
            {"Gatecoin.com-2", "195V4ePpHfNVUF19Bwv4v5gaepVAVuM36C"},
            {"Gatecoin.com", "1JqZh9eB7MbGks1x7PMj1Ksk9KBKvoGMZ2"},
            {"CleverCoin.com", "1Ge6vrZiYyPX6CpDv2hKhkk6PLCHLuZYbB"},
            {"Banx.io-old2", "18Wi7EMwnPmZeWHHHAhdJdTLEv23qhbcos"},
            {"Banx.io-old", "1KfHkg7FBidcMk6W4HDd9m3wxHaKUkzdLN"},
            {"Banx.io", "1FMvaN8SdDSsaDABVqETxeqf8BDD5gLrTu"},
            {"QuadrigaCX.com", "1L5Duj4K7NxV8D9y2eWDdkYCeeBK3T53Ve"},
            {"BitKonan.com", "1GEp9Fui9XmyVhszPzFazdW3WHyt1adLR6"},
            {"LakeBTC.com", "18etDe6HsVFWSGv8fbW9Qn7eBrSsYa32uh"},
            {"OrderBook.net", "14QdBtAhexfupgR2pyhNULWVTwDKbethrm"},
            {"Coinomat.com", "14bYTf7fqMm3Eh12Y59T5DbfEmm8QrfWtu"},
            {"MeXBT.com", "1EApiQihSg3DPVG8kmVCeq5kehLjXPm2Z1"},
            {"CoinCafe.com", "14sPPzbuRdgXMTMAAvThciX7GSjsuGmc39"},
            {"BTradeAustralia.com-incoming", "1XYq2tLwNxM15sqEtbgpSph75HRgZkTFr"},
            {"BTradeAustralia.com", "1Nznb9Szo3Vx9njDUU5eVgqEe8YqiV5Uwx"},
            {"UrduBit.com-cold", "17W4PZ2PS3KksDy5T6yE7FaJsgjmnYMXuP"},
            {"LiteBit.eu", "1Go7vvmLfKeu88m2zRzbuztfkLDfxbLJk5"},
            {"Coins-e.com", "1LLHYQsnQ7DGhFU4hPqgk8DfDwxvq3zxac"},
            {"ChBtc.com", "1H2QU8im5Ed1fkDuAUXwLDZnLF21NmUfFg"},
            {"HappyCoins.com", "1DhZK44qx7dFL4K5qYWjLefhZfdCcuzVnp"},
            {"BtcMarkets.net", "1H8maQ7Xi7Fv1PBXwXLznjYJGdEhcSpqGY"},
            {"796.com", "14EBC92evNCak2PqubXJshG5KPjnyajC3H"},
            {"Vaultoro.com", "1227RVexDc3YX9FtbtKyJPF3RLT2z88g3v"},
            {"Exchanging.ir", "1Ks5aLkREyVUba3QiS64ZL5PPdcgXDXhBp"},
            {"Korbit.co.kr", "1GrCCd4mSvxLqKFzs8Pbny9qBqL65LFKJp"},
            {"Coinmate.io", "1B79f7FHpvwxcpBGfaRnFeBkjtvfipj5vw"},
            {"BlockTrades.us", "15ZZ98fghx6pRtTTULPkXbXwX2kZUD2Yp2"},
            {"Bitcurex.com", "1CEXQdnhAoxYYWZRy7e3EBD46rnLba79KC"},
            {"CoinTrader.net", "1HwMuq4Ch7HiMtQ7is4ea5d7wSJjxuJAZi"},
            {"CampBX.com-old", "14xEYv1Ehv4doypfw48RGMmDkUMZrp8Fai"},
            {"CampBX.com", "1FaoUMnUHHy495jKNViLuPDoVPNK3uK3PG"},
            {"FYBSG.com", "1FTo7d15fgenrJHAWN8TpixggocscterLC"},
            {"SimpleCoin.cz-old5", "1732nSxjfAj1Z9pBiaAgtk4ekA7Bm3Z9na"},
            {"SimpleCoin.cz-old4", "14hQAwFGRCNEmtsEYizbiSyMrhyr5VsNiw"},
            {"SimpleCoin.cz-old3", "1Bgytxtbvmj7B2DTEHYQmmNiwgdbvxjyQV"},
            {"SimpleCoin.cz-old2", "12xnb8qNjRGeL2J3rJoeFrqNBJwQFaMrkt"},
            {"SimpleCoin.cz-old", "1927zCBQXa6nG4ZaTDNtaek4ubHpEbJGxP"},
            {"SimpleCoin.cz", "13N69SPqEJTLNDH3v4d4Ux7nZsABRyhpur"},
            {"TheRockTrading.com-old", "16MCtYAHyUMPvLKWihBYG5TdQwRNfKoLLn"},
            {"TheRockTrading.com", "3HgVJYzT15Wpzotan77obCFvQwrGGX371Y"},
            {"Igot.com", "1GS2inLB6jaqUuu7hpgVKociwPGEMMctkg"},
            {"CoinMotion.com", "1Msdj4ivRDzWgqyY3MAWVLx9Mp1qQw7mto"},
            {"Btc38.com", "1CELa15H4DMzHtHnuz7LCpSFgFWf61Ra6A"},
            {"Exmo.com", "1MynxXAan9JWpwCXD5ZtY5UongLyRrimx9"},
            {"BitVC.com", "1Bzcrtsy3FjrTmTbB8dsvBmGGCsadnXPFW"},
            {"Vircurex.com", "1HemKhiiRRhk6YVvUdcyJAWbHEwpGkUaYM"},
            {"FoxBit.com.br-cold-old", "3EKBC9BWM6LaZTt2YZm2QWPo7euvfE69tP"},
            {"FoxBit.com.br-cold", "3KAuEYkuJQw1Ad2GzWjfC7V5XoL2fCqjGN"},
            {"FoxBit.com.br-2", "19WpAEPtfxbzhndCSrwzXnUyMeSB6pdmWV"},
            {"FoxBit.com.br", "127LFXb94xZeDrn5Ch4GqcMrjzhBCpKcBu"},
            {"CoinHako.com", "383nfCpJQWsbHB9adJjjRL3YoZHuNFc7TR"},
            {"C-Cex.com-old", "14ucsjZBmGKAZhJtG46AwhcjdDL9F2tc89"},
            {"C-Cex.com", "1GFNZ8B1Ax1ft8yPy3qLiDvVafTCeM84gs"},
            {"Cavirtex.com", "1AdVABFi77GTdPL6NBmT6LJSedwxXucB5N"},
            {"SpectroCoin.com", "1NaHRVrrozEcQbymLHicXMXDXXEM4eK5W9"},
            {"BitBargain.co.uk", "13MZDNwKWCvyAW3Lqpp3A6q4gNXkB64sUp"},
            {"Paxful.com", "1NysS6A4XaStAFt9RRnMZLoP6sVWxHQC7e"},
            {"VirWoX.com", "1Gt2CptfVnE5ULfvDjsDVTNU7rqWaSsUMo"},
            {"Bit-x.com", "3ErW3bMinZtcRBbzD2HdypbcBzKzDGw6ij"},
            {"Matbea.com", "1BZEV8YKTLZGDgSkyJjR4M9ZMA39Um6Srh"},
            {"Bitfinex.com-old2", "15ebQxsrRRUwYFaqfmcgbC2hnYrq6Y72oM"},
            {"Bitfinex.com-old", "1M3xjgBs6ELSKRxJ2tj4M41LoRgXrhSCjN"},
            {"Bitfinex.com", "19VNw8EQWKTmN7u1X15hqyWHrymrCCVWdK"},
            {"Bleutrade.com", "1F8bQguTws8P64d2otjMVXqxGmdgwymer6"},
            {"CoinSpot.com.au", "1JQCTbXa3BZVMqE41wuSW6GpfybdhZVxJn"},
            {"AnxPro.com", "17sLQNY8UAPrGdC7F2iFHbJDYFdctdRKqb"},
            {"BitBay.net", "3L676rAfFZ9JXRaEgFiwKuT6wgLkC23UWw"},
            {"Hashnest.com", "185oYS2RwHWudHNQ5UM6gpyx7iNKTEtj3q"},
            {"Bter.com-cold", "1NFeBp9s5aQ1iZ26uWyiK2AYUXHxs7bFmB"},
            {"Bter.com-old3", "1KrnUjLNN6wmK9fB7En9kojuvJHB6sCVTJ"},
            {"Bter.com-old2", "14kdQG5VxRKUEG1L8Qi6GKr1S8vKSGAnpx"},
            {"Bter.com-old", "17cFV8dT7GJLdxp1meCWjFBTfHcBQZ1GQZ"},
            {"BX.in.th", "1GturjXqM4hzM7HHp75wPdG4ezr1HtNpPt"},
            {"BTCC.com-old2", "1AUoThb9mXukzbjahmxa4EQpn2EFn4qPiP"},
            {"BTCC.com-old", "1KdTXCdP5t8xJ31zaSFktCjyxWWerU28eX"},
            {"BTCC.com", "1KxPDLUDKstHbTKALuLH8MtzFaJsaBJhqi"},
            {"OKCoin.com-2", "1L9xAUEPegUc7oB9mPWRiS4GEumetDjrdw"},
            {"OKCoin.com", "1Mkpy74Gczz8TNTjg8xjjaEugn7FD5QhUf"},
            {"YoBit.net", "1FU2uVBCpAeGDmEjqmwEi9mzwe19vAsjhm"},
            {"BtcTrade.com", "1AqirJrxm8iWnmxN3q8Nt9LHCVRRpwi76t"},
            {"Cex.io", "18b1GwzMpZYsSSrKVf4WYPuXULyoMf6Kwo"},
            {"Bitcoin.de-old", "1JGfZKnBkT8gbtp53wWZqQKUPBQHW86q1V"},
            {"Bitcoin.de", "13iMZjXxQuq8WpsrVrEARouGiwa7Ec41mz"},
            {"Cryptsy.com-old", "1HpeCDwDxdB1Ad5Fx1QdSyPoWv2AUuuGoT"},
            {"Cryptsy.com", "18kKnQjFz9rfYSwJhsBF8y4fksXCnAkfg1"},
            {"MercadoBitcoin.com.br", "3JkSwgHew9QBsFNufrw4qmMW5mAnQJZXeA"},
            {"Bitstamp.net-old", "16PMJGm6TE2Se16wRf9xuGFYiJBnT1FVAN"}
        }},
        {"Gambling", {
            {"MineField.BitcoinLab.org", "19mS9jJD5srCNwDVJetQRrUYnnhWQGmJc"},
            {"DiceCoin.io", "1CYju8vZYKytTQDmvRxBggeVYRPSvAFmoi"},
            {"FairProof.com", "14AfRero4nGxvPdRTF3A4GytDHbppJvD4o"},
            {"DiceNow.com", "15rM6EwpqdSG3CX1ZGK5VeLjQAXZ5zg1z3"},
            {"BitcoinPokerTables.com", "1Gko7FZ3S5btD837ryZrkJvmQ9SfYwT5kW"},
            {"BetChain.com-old", "15KXokwircziJ1Z9PS3JKhdVniwTxrEKSd"},
            {"JetWin.com", "1KTrWTMsB7zYADPFSCPnisBEYYzAhLXsdN"},
            {"BetMoose.com", "15VJ81oggAR7cEtyh8YZGeCsWjqKJpNgKn"},
            {"CoinRoyale.com-old2", "16PDHmBRKLxCvzttLJvYjj2aDVPryt54a2"},
            {"CoinRoyale.com-old", "1M41nU3P7apHs7KtyjnZaegEBSyL5EaX9m"},
            {"CoinRoyale.com", "1FFwxD2C7DUohz4m5BW7h4yzCqm48dBPHd"},
            {"Coinichiwa.com", "1CeqPhoTFbX8zq3wWCFUbt7g5C3TDbQFsD"},
            {"SatoshiCircle.com", "17A6DADegGu96yLQdVe71KLEx2x7vW6asi"},
            {"BitStarz.com", "1Q5X43DKVF1R8XM1MsyquCaNmNrzzmaReV"},
            {"777Coin.com", "1E421ChpHWEqQ2Kcy2JqEE8eDx7nFN4AXj"},
            {"Satoshi-Karoshi.com-old", "14mXxHFQeUYjQMraNMsB6hPFhwsAQSMZqj"},
            {"Satoshi-Karoshi.com", "18s7KGN3htDhKZSSuJDFFgSCXyEomgzXTT"},
            {"AnoniBet.com", "1AMqnsRgbMjqZLPqBQPuuX7THgorF8WngM"},
            {"Peerbet.org", "15qJZk4qh9fqEkrMLKfxQXmBk3WdnQ9T7R"},
            {"BTCOracle.com", "1Up15Msx4sbvUCGm8Xgo2Zp5FQim3wE59"},
            {"SatoshiRoulette.com", "13Lyp8iawQyyychG6aHe71UkkNp53cR6DW"},
            {"SwCPoker.eu", "1FJWNZnYrA5ptLmreBzdXCnPXa9cHiqR2B"},
            {"Betcoin.tm", "1BTPSjiSC1s3A5cqJrbDRi2LAHx3U88mKR"},
            {"Crypto-Games.net", "1JKhUULaWYnaNUouSkKbXEmqCBMB61pnQq"},
            {"Coinroll.com", "1BKSARZdi7vyBvTv4LRW9QGe3cvfuCBjsz"},
            {"YABTCL.com", "1PhmMsdwamJA6soKw5mNMXxzGomHEHWY5P"},
            {"SafeDice.com", "1DbJch2YpcFNaXsw1tvoRPUErpydUnunj6"},
            {"SatoshiBet.com", "1AX18zUCf1CwW4PNPXa6b7kmJPgM6vFAs9"},
            {"Betcoin.ag-old", "1JzVYbjEA49w6zMhKJ6PssUoKpooK6KKgF"},
            {"Betcoin.ag", "17hiCXtpyFKXMSzGD3Tt1xqfTFK5Jt9mWB"},
            {"BitcoinVideoCasino.com-old2", "1MWwPwmJyPfCMtq9fDcxiYhXMxndeZtjfL"},
            {"BitcoinVideoCasino.com-old", "1MkuYk9nk19Wyh3k285mfo9ru8S9vVt7G4"},
            {"BitcoinVideoCasino.com", "1KpnaXqHgEut1LCaE1maLZBKgAgEu8G7QF"},
            {"BitZino.com", "12DzK5gjSEYbmBZUn3XkQ9ypmytHNpvjDC"},
            {"Rollin.io", "17BKLPRpdqmheEC6q8AmJJP39a2JiKWVpT"},
            {"FortuneJack.com", "1HzhKuP2T3EcdixARtM1KpccGbdJczZTYu"},
            {"PocketDice.io", "1Nrj7LXt6pzVGd9q6vWpFy2pkuDrsfxNwZ"},
            {"SecondsTrade.com", "1ARF7D3a1CTUP2ej3UNuLSY54VnftKNfPm"},
            {"NitrogenSports.eu", "1EDLW1yYXciLunPs2o1hCsiM3v6HwStvbR"},
            {"SatoshiMines.com", "1545LBUF2CZCkwbrUuaedgNskcXtdbhsYV"},
            {"CloudBet.com", "14MjzDa34KwQBRfxkKkbnUWsMSg5VUnB4K"},
            {"PrimeDice.com-old4", "11223UDswFBFbMJ75r3K8epaqX6ZxQpPVd"},
            {"PrimeDice.com-old3", "1MsgD1v4dqGPkCjbBoLHZqJNybyMXZNDf5"},
            {"PrimeDice.com-old2", "15CWJpAe9rLFLQPrsqPiViu2iS4yUEKFEh"},
            {"PrimeDice.com-old", "1Bm8BfJPGZaaDTAwqP2pE4twsR1oyTjw1y"},
            {"PrimeDice.com", "1H2s3ZSXuYKKXp8SvPki851FghJq5q2sH4"},
            {"CoinGaming.io", "1LkEiNuK47XdoQLiMBhYEEZvz3iUDqQhQP"},
            {"999Dice.com", "19b1n3JNMf49hNmifQapxBhQFnjnzERtvQ"},
            {"BitZillions.com", "1bonesRuyoUhAAe4a34nRXtzRy6JP3w2P"},
            {"LuckyB.it-chatbot", "161gTqw3CHVqiBfmC3vCLrXPob6wLQSKP4"},
            {"LuckyB.it", "1NxaBCFQwejSZbQfWcYNwgqML5wWoE3rK4"},
            {"SatoshiDice.com-original", "1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp"},
            {"SatoshiDice.com", "17zPbPAhfALYcxR2SAEHu4XZLXZYQoyzV5"}
        }},
        {"Services/others", {
            {"GreenRoadMarket", "1Q99AKghHJ3VEWA6UGTWJrE7icSWRhozRF"},
            {"Bylls.com", "14jpsTvys7mqecHC851xJpj6wF6pQDyaXF"},
            {"SecureVPN.to-old", "1Bvuydv84ZMdzrHfrdThdgLKqEdG14pGsx"},
            {"SecureVPN.to", "1Cw3xr6ZxBKEzCSTkCwryip5GU6MNLHpPZ"},
            {"Vic-Socks.to", "147VmekydXM2JvJpX5sXbYWgGkEHVUgEHa"},
            {"BitClix.com", "1ABEzWJpiKzzhy8wyUHUKevkB1pdcL9vXv"},
            {"BitLaunder.com", "1ET9RCoy4yfRxSXEnpHibKzp8mfqDMikMb"},
            {"WatchMyBit.com", "146QyVLdpsLmdbzswtwkuWboNt8YqRJZji"},
            {"CoinWorker.com", "1Codxq4pdK72K6vDMQEhhmat2eVCcJ1XUX"},
            {"CoinBox.me", "1cointQVgw2EwnJx3EFVPvD65gSsD9nJ7"},
            {"BitNZ.com", "1BrF8iYUJAzngDV2j2sU7dmnMhBmTB7NJs"},
            {"CoinURL.com", "1JMsrs5eUZGDrwhHNDHJuJiW3mazgjxRjk"},
            {"BTCLend.org", "1Efd2nct3eUijTLmmxRxcPWUnUJ8YDVLbr"},
            {"BTCPop.co", "1KLktTKdGXkQGtL788ZdJt8bBT9Kr9ySjJ"},
            {"GoCelery.com", "12sUDSyw79pxFP1nP2aB519VXF9noAsgaG"},
            {"DoctorDMarket", "1MkDc8o82PEVhRcW2uxEDdpjHrRrTVs9rU"},
            {"ChangeTip.com", "1AwLahmayYFYY2qWBciXh2KKFjRKqc5Urr"},
            {"Genesis-Mining.com", "1MpAJJ3z1SuKzUpstRWyWJGvwnpyTzD3Nf"},
            {"CoinApult.com-old", "12QFkzXR7vGRb2JkLo1YvsP1ioiADZJWQp"},
            {"CoinApult.com", "3Pu3SEE5hEdQTvLWWXBiBBmWzQNpyoTq5f"},
            {"CryptoStocks.com", "1JCrjaVU6TsgdGRBcQ7RjemckM8pWBPMjK"},
            {"StrongCoin.com-fee", "1STRonGxnFTeJiA7pgyneKknR29AwBM77"},
            {"Bitbond.com", "1E4BZfG7uLMivuRLTa1k2CVQDUPmvpxGXJ"},
            {"Paymium.com", "1MS17CwusivpXaBSf1CgQ9VcnRdco4FwUm"},
            {"GermanPlazaMarket", "1EPHNmtCnWZU4A7Vm68TDHmKrHoGaQ9GuA"},
            {"Loanbase.com", "12fnqJqEfEjTVnkhEPYjhXrRD1i6bZZeZg"},
            {"ePay.info", "1PY3ziMwTMwDLryXdb3WsfPaN637jpwXbv"},
            {"Purse.io", "1PBxY3VH7w4PmbRG4nJBJYwZt92Mc9gn6U"},
            {"OkLink.com", "19FbJLrD6BjaS1bh5jHHvNyyGFQRTj6waL"},
            {"FaucetBOX.com", "1AUvrDGLJNeGFQ5RL5HAxzCyvq2fXsinTS"},
            {"BitcoinWallet.com", "17zxRxWZa2hFLooGcQ12DTo8qWYSNBMbkp"},
            {"MoonBit.co.in", "358Yqigs4eYDYCy7v7qDxyeGevUJKLeJP3"},
            {"CoinKite.com", "1K17CWKGb74yk6C64wQ9iyrdgUwN6ifNQw"},
            {"BTCJam.com-old2", "1JceroDThChGfsfTC2ZbGjafPQoFm5mZbF"},
            {"BTCJam.com-old", "1NP5HCMVBWArhi4Y5yL81VySEvLYVp1zVW"},
            {"BTCJam.com", "16293iX5ynGo2saLFQDxiTX3a7r1pshCD2"},
            {"HolyTransaction.com", "3CtoEL3sDZeicbSbNoQ6kmQifv3Gf652MP"},
            {"HelixMixer-old34", "1JHAA7vmqTFSS1jNyAowc9FVeRQGaFy4Je"},
            {"HelixMixer-old33", "14DuqSWCMbzGHbADMU2wWXpYVkJ2WE2haC"},
            {"HelixMixer-old32", "1Nx4U1R68RSGnyRVYJEeGPKAeUCc1b6dcd"},
            {"HelixMixer-old31", "1o8oiSQxi3uLqFcAY7N26gX6pYhPAw32W"},
            {"HelixMixer-old30", "1BKgEFCRctnwU7WtK1oNZ3SxWYdgdg6cr2"},
            {"HelixMixer-old29", "1NEEGcyyhSEMQfCpcxK8EfTmmzPK2EXZy7"},
            {"HelixMixer-old28", "1EA5e8n1bCNf41nVp69A1wvxZZka4AXrUM"},
            {"HelixMixer-old27", "1CZYYubgBxgiuBERZEjjDRRhvnx4FrzE6g"},
            {"HelixMixer-old26", "1CTxEoAzjPLjcnsBcHFdnyJTTqsTAy7iUh"},
            {"HelixMixer-old25", "1JG4bYqpmtQnx6xFEaDHJ1iQ8SaBozNcm9"},
            {"HelixMixer-old24", "16ePYbXMHHmYMnYm1HdHnav2FuDzjNW78i"},
            {"HelixMixer-old23", "163694H4EYkgfkmrc7xPMD9L7xXrMPVRuW"},
            {"HelixMixer-old22", "1J17KMFx2e1CqdfT9W7sCiXSnciLy1P69G"},
            {"HelixMixer-old21", "1GWtnJS4kQvwiBnaKG4xiEarxtBBFCoCtC"},
            {"HelixMixer-old20", "1ANi3WHvgDK1yU4R1FzvUa72dr1RcBo3BK"},
            {"HelixMixer-old19", "15bzwpNfPDDDFfZMa9aTUQsRnVSNpZ5yBa"},
            {"HelixMixer-old18", "1BAwqs1QfGRqLAMhCYqdBgvCG1uC14zvQS"},
            {"HelixMixer-old17", "1KGfTgYDqG68KZ1xXVcGXsbFmZF2rRjsqt"},
            {"HelixMixer-old16", "1Q17aKSoJbRo491ebWFtttstzda1u7RsQD"},
            {"HelixMixer-old15", "16nE8auRFJiMvWrSMFg7fkWUeK8TzQpgk6"},
            {"HelixMixer-old14", "1EDHM35LjPQSkhwH9y4tqRSaqieEoSzJav"},
            {"HelixMixer-old13", "1G9PNV4iByjAqnUWK1yZiXuB1gZiPZusAe"},
            {"HelixMixer-old12", "19jKH32cj8JuoR61XK95fVYfLjr3JXbAFj"},
            {"HelixMixer-old11", "1CAgVpTPUGn5Uwj2ezwjzSqrTF6XwRUqxu"},
            {"HelixMixer-old10", "17gUEZyrp5CkjBh9gFFsQQcy9DEGKgAp9s"},
            {"HelixMixer-old9", "1BH1fSgHPPcXc5ZSiuXeKTrV5cgDj2nStp"},
            {"HelixMixer-old8", "1AicGHJVVgRzegSXFaQBPMGYVnjwDQ5Lmd"},
            {"HelixMixer-old7", "1DhYsLaU31qFWAm4R7ZBgPx11uterEESD6"},
            {"HelixMixer-old6", "1H2FkVmRmKGjeaBbw6gk5nN1TGADyUaeyF"},
            {"HelixMixer-old5", "1Dk5PVnBpyaERQQfigoC9TRkCRZ7Cv2Sg3"},
            {"HelixMixer-old4", "1GzzSJ34U8mxWy1UKCfzo7NpFzuKvaCSQ9"},
            {"HelixMixer-old3", "1J9pv8isXpRL48sbWi8NemQDnU1ZPgF2wo"},
            {"HelixMixer-old2", "1EX523Hfsh9RMpzJZUQuiZzNWWVxAstuey"},
            {"HelixMixer-old", "1Kj24xgnei6RqCDZ6gefJxCc1LvW7FyvYs"},
            {"HelixMixer", "13642EkbFPxomz7pZ8eAdGXyTTXp9zRTb2"},
            {"CoinJar.com", "1DrtdJnp6Cx5RSx5kJpnGwRiMpLr4o1ZYk"},
            {"BitcoinFog", "13R8zZq4pg258fcHfvE67mbuCDMkeDNt86"},
            {"NucleusMarket", "1LDM7MdmimPdyKZLZnmJoRUqRcjHMsakkC"},
            {"AlphaBayMarket-old", "17DEJSAMHsTtsxZA1v6yu51xVwtFJ5ECfp"},
            {"AlphaBayMarket", "14geEFfPXT9K5Vao9DcoFeikPDJyc7QZUM"},
            {"HaoBTC.com", "13hQVEstgo4iPQZv9C7VELnLWF7UWtF4Q3"},
            {"Cryptopay.me-old", "1HrHsgAuHrHYJHVWPpgm8YkjtcyFxBSBKt"},
            {"Cryptopay.me", "38Jz5AobqyWgUkbBFa2ANH42JofXARB98e"},
            {"BitoEX.com", "19vocJmgQ8gRhSZe4rgPvPGeB6HHvXjxtC"},
            {"Cryptonator.com-old", "16ttqBTMimk3w6veGF3MV4t2Ln56SiFhPc"},
            {"Cryptonator.com", "1GW2Xor6tkbdXaecEaUXbE9e1bcBNYWk7a"},
            {"BitPay.com-old3", "1QDMykW6y1v5aUUBAoXjRUBMzC7euEEVts"},
            {"BitPay.com-old2", "115gF9GA8qfxEXp9UjhVzRUwp3yvvvu6hN"},
            {"BitPay.com-old", "1PEoUKNxTZsc5rFSQvQjeTVwDE9vEDCRWm"},
            {"BitPay.com", "1ArJTD4iR3SCwjuyiP3H6pbwvPBHduX6WB"},
            {"Cubits.com", "1CAxhfNvk1xEtMuS4J8b1TrZkifReevW5s"},
            {"CoinPayments.net", "3ASwRxA2Dg5A8dhiDVZc4VV1E8Zt78qP6A"},
            {"Xapo.com", "3LVDJtQFBDpqCPyKJPPaYs5vriAgPqWjYR"}
        }},
        {"Miner", {
            {"Telco214", "1DXRoTT67mCbhdHHL1it4J1xsSZHHnFxYR"},
            {"Kano.is-old", "13pucx6gHP2vyBLc88QfcGivjkhK63PeVg"},
            {"Kano.is", "1N6LrEDiHuFwSyJYj2GedZM2FGk7kkLjn"},
            {"Eligius.st", "1JkT6EQMotCz6BFqPWFd3kFDQzU1qa119N"},
            {"BW.com", "1JLRXD8rjRgQtTS9MvfQALfHgGWau9L9ky"},
            {"Bitfury.org", "1FeDtFhARLxjKUPPkQqEBL78tisenc9znS"},
            {"KnCMiner.com", "1H1sq6Msgt9HjRrBuz8ieZdThzWXS6oPVA"},
            {"EclipseMC.com-old3", "1B55K4WuR1AQKCmF8WznDmhZNw6G1x8uEc"},
            {"EclipseMC.com-old2", "187b1MZr73iuPGnABu6d4eSYmt2NQHkTqt"},
            {"EclipseMC.com-old", "1NfJfjsyfxJ9zoA1LPj4TdDHf8mSUvQ17r"},
            {"EclipseMC.com", "18M9o2mXNjNR96yKe7eyY6pfP6Nx4Nso3d"},
            {"BitMinter.com", "19PkHafEN18mquJ9ChwZt5YEFoCdPP5vYB"},
            {"AntPool.com-old2", "1Mp3atombUR6iLLYoLEdN9uPfPscsKBXfi"},
            {"AntPool.com-old", "1GuMujABuc8kvzDTyVJFpcf4vszPUgsjiU"},
            {"AntPool.com", "15urYnyeJe3gwbGJ74wcX89Tz7ZtsFDVew"},
            {"GHash.io", "1CjPR7Z5ZSyWk6WtXvSFgkptmpoi4UM9BC"},
            {"SlushPool.com-old2", "1AqTMY7kmHZxBuLUR5wJjPFUvqGs23sesr"},
            {"SlushPool.com-old", "1Mining2pfZRiFxGBQ6Jw8YNheUkHhyMfn"},
            {"SlushPool.com", "1CK6KHY6MHgYvmRQ4PAafKYDrg1ejbH1cE"},
            {"BTCCPool", "152f1muMCNa7goXYhYAQC61hxEgGacmncB"}
        }}
    }};

    return tagsMapping;
}
